### ISSUE TITLE
Consider using `get-port` instead of Math.random

### ISSUE THREAD

**Issue by Lange** [nrkno/tv-automation-atem-connection#23]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
The `_createSocket` method currently relies on `Math.random` to choose its port ([`src/lib/atemSocket.ts#L130`](https://github.com/nrkno/tv-automation-atem-connection/blob/4086ddb0bda6133afbcfd4b847cafca5a9dc9f84/src/lib/atemSocket.ts#L130)). This is not guaranteed to work, and could result in startup errors if it chooses a port already in use.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
A better solution would be to use a library such as [`get-port`](https://www.npmjs.com/package/get-port). However, this would make the `_createSocket` method become asynchronous.

**Comment by baltedewit** [comment]
Yeah, the way we do it could be a problem statistically seen. I think we need to take the basic idea `get-port` uses and adapt it to test `udp` ports.

`_createSocket` is an internal function so we can change it without any worries.

**Comment by Lange** [comment]
Good catch, I didn't notice that `get-port` was specifically checking TCP ports only.
